#server:
#  port: 5000
#
#spring:
#  application:
#    name: Fitness-User-Services
#
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: fitness
#    password: root
#    driverClassName: oracle.jdbc.OracleDriver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true



server:
  port: 5001


# Spring Start
spring:
  application:
    name: Fitness-User-Services

#  data:
#    mongodb:
#      uri: mongodb+srv://admin:gsk3E1ZwjWwgqAoC@cluster0.9xkoq.mongodb.net/
#      database: eqipped_new
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: fitness
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  # Optional: Connection pool settings
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      pool-name: OracleHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

