rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  exchange:
    name: fitness.activity.exchange
  queue:
    name: fitness.activity.queue
  routing-key: fitness.activity.routingKey

