

server:
  port: 5003

spring:
  application:
    name: aigeminiservice
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/ # local docker mongo db docker container
      database: FitnessActivity
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka