server:
  port: 5002

spring:
  application:
    name: Fitness-Activity-Services
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: FitnessActivity
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka